services:
  db-user:
    image: mongo
    environment: 
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    ports: 
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - stock-consult-network
      
  redis-logs-user:
    image: redis
    ports:
      - "6378:6379"
    command: redis-server --appendonly yes
    networks:
      - stock-consult-network

  api-user:
    container_name: api-service_api-user_1
    build: 
      context: .
    ports:
      - "3004:3000"
    depends_on:
      - db-user
      - redis-logs-user
    networks:
      - stock-consult-network

networks:
  stock-consult-network:
    external: true